### ISSUE TITLE
Crash to menu shortly after Luck effect appears

### ISSUE THREAD

**Issue by 74HC14** [TeamMidnightDust/Celestria#2]
https://mclo.gs/HpepEkj
Latest crash at "3:34 pm", though others of the same type are in the same log. Had 4 in one day. I am playing with a fair few other mods so it may be a conflict of some sort, but PolyMC's only "suspected mod" is this one. I can only see the normal vanilla sky after entering into the game again.

**Comment by Motschen** [comment]
Well, I developed the mod on 1.19.2, so I guess it doesn't work that well on 1.19.

**Comment by 74HC14** [comment]
Ah that may be the problem. I'll see about updating after work and hopefully that fixes it.

**Comment by 74HC14** [comment]
Ah, the modpack won't update without a complete rework. Feel free to close this issue if you don't plan on backporting the mod to 1.19.0.
