### ISSUE TITLE
Use action bar instead of chat to announce shooting stars?

### ISSUE THREAD

**Issue by sisby-folk** [TeamMidnightDust/Celestria#3]
Hi hello! I'd like to suggest using the action bar above the toolbar (right above where item names come up when you scroll through them on the toolbar) to show shooting star announcements, instead of in the permanently-logged chat.

The text may need to be shortened (`A shooting star has appeared in the sky - how lucky!`) to suit, but I think it would be a more seamless experience

**Comment by Motschen** [comment]
Changed in 2.0.0, thanks for the feedback!
